require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'AsanaWorld' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'

  target 'AsanaWorldTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11'
      end
    end
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'AsanaWorld-tvOS' do
  # Pods for AsanaWorld-tvOS

  target 'AsanaWorld-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
